from typing import List


# Replace pass with your solution
def collatz_sequence(n: int) -> List[int]:
    """Return a collatz sequence starting with `n` as a python list

    A next element in the collatz sequence is generated by:
        - n/2       if current_value is even
        - 3*n + 1   if current_value is odd 

    Examples
    --------
    >>> collatz_sequence(1)
    [1]

    >>> collatz_sequence(2)
    [2, 1]

    >>> collatz_sequence(3)
    [3, 10, 5, 16, 8, 4, 2, 1]
    """
    if n == 1:
        return [n]
    return [n] + (collatz_sequence(n//2) if n % 2 == 0 else collatz_sequence(3*n+1))
